// Topic catalog library: load, validate and render topics/catalog.yaml.
//
// Pure functions (no network, no cluster access). The CLI in generate.mjs
// writes or checks the rendered files; tests in test/catalog.test.mjs.

import fs from "node:fs";
import path from "node:path";
import YAML from "yaml";

export const TOPIC_PATTERN = /^evt\.[a-z]+\.[a-z0-9]+(?:-[a-z0-9]+)*\.[a-z0-9]+(?:-[a-z0-9]+)*\.v[0-9]+$/;
export const NAMESPACE_PATTERN = /^evt\.[a-z]+\.[a-z0-9]+(?:-[a-z0-9]+)*$/;
export const EVENT_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
export const EVENT_TYPE_PATTERN = /^[A-Z][A-Za-z]*\.[A-Z][A-Za-z]*\.[A-Z][A-Za-z]*\.v[0-9]+$/;
export const SERVICE_ID_PATTERN = /^svc-[a-z]+-[a-z0-9-]+$/;
export const K8S_NAME_PATTERN = /^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/;
export const IMPLEMENTATIONS = ["outbox-relay", "debezium-outbox", "legacy-topic", "contract-only"];
export const CONSUMER_STATUSES = ["known", "unknown"];
export const MAX_TOPIC_LENGTH = 249;

export const GENERATED_HEADER =
  "Generated by scripts/catalog/generate.mjs from topics/catalog.yaml. Do not edit; run `npm run catalog:generate`.";

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

export function loadCatalog(filePath) {
  const doc = YAML.parseDocument(fs.readFileSync(filePath, "utf8"));
  if (doc.errors.length > 0) {
    throw new Error(`${filePath}: ${doc.errors[0].message}`);
  }
  return doc.toJS();
}

/** Parses the bootstrap manifest CSV (no quoted fields in it) into a Map keyed by service_id. */
export function parseManifest(csvText) {
  const lines = csvText.split(/\r?\n/).filter((l) => l.trim() !== "");
  if (lines.length === 0) {
    throw new Error("manifest is empty");
  }
  const header = lines[0].split(",").map((h) => h.trim());
  for (const required of ["service_id", "event_namespace"]) {
    if (!header.includes(required)) {
      throw new Error(`manifest header lacks column ${required}`);
    }
  }
  const rows = new Map();
  for (const line of lines.slice(1)) {
    const cells = line.split(",");
    if (cells.length !== header.length) {
      throw new Error(`manifest row has ${cells.length} cells, header has ${header.length}: ${line}`);
    }
    const row = Object.fromEntries(header.map((h, i) => [h, cells[i].trim()]));
    rows.set(row.service_id, row);
  }
  return rows;
}

export function loadManifest(filePath) {
  return parseManifest(fs.readFileSync(filePath, "utf8"));
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function kebabToPascal(value) {
  return value
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

export function dlqName(namespace, major) {
  return `${namespace}.dlq.v${major}`;
}

function isPositiveInt(value) {
  return Number.isInteger(value) && value > 0;
}

function sortedUnique(values) {
  return [...new Set(values)].sort();
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/**
 * Validates the catalog against the naming standard and the bootstrap
 * manifest. Returns a list of error strings; empty means valid.
 */
export function validateCatalog(catalog, manifest) {
  const errors = [];
  const err = (msg) => errors.push(msg);

  if (!catalog || typeof catalog !== "object") {
    return ["catalog is empty or not a mapping"];
  }
  if (catalog.apiVersion !== "catalog.fintechbankx.io/v1alpha1" || catalog.kind !== "TopicCatalog") {
    err("apiVersion/kind must be catalog.fintechbankx.io/v1alpha1 TopicCatalog");
  }

  const cluster = catalog.cluster ?? {};
  for (const key of ["strimziClusterName", "strimziNamespace"]) {
    if (typeof cluster[key] !== "string" || !K8S_NAME_PATTERN.test(cluster[key])) {
      err(`cluster.${key} must be a Kubernetes name`);
    }
  }

  const d = catalog.defaults ?? {};
  for (const key of ["partitions", "replicationFactor", "minInsyncReplicas", "retentionMs", "maxMessageBytes"]) {
    if (!isPositiveInt(d[key])) {
      err(`defaults.${key} must be a positive integer`);
    }
  }
  if (isPositiveInt(d.minInsyncReplicas) && isPositiveInt(d.replicationFactor) && d.minInsyncReplicas >= d.replicationFactor) {
    err(`defaults.minInsyncReplicas (${d.minInsyncReplicas}) must be lower than replicationFactor (${d.replicationFactor}) so one broker can fail`);
  }
  if (d.cleanupPolicy !== "delete") {
    err("defaults.cleanupPolicy must be delete: domain events are immutable facts, never compacted");
  }
  for (const key of ["partitions", "retentionMs"]) {
    if (!isPositiveInt(d.dlq?.[key])) {
      err(`defaults.dlq.${key} must be a positive integer`);
    }
  }

  const services = catalog.services ?? {};
  for (const [serviceId, svc] of Object.entries(services)) {
    if (!SERVICE_ID_PATTERN.test(serviceId)) {
      err(`services.${serviceId}: not a service id svc-<ctx>-<capability>`);
    }
    if (!manifest.has(serviceId)) {
      err(`services.${serviceId}: not in the bootstrap manifest`);
    }
    if (!K8S_NAME_PATTERN.test(svc?.k8sNamespace ?? "")) {
      err(`services.${serviceId}.k8sNamespace must be a Kubernetes name`);
    }
    if (!K8S_NAME_PATTERN.test(svc?.serviceAccount ?? "")) {
      err(`services.${serviceId}.serviceAccount must be a Kubernetes name`);
    }
  }

  const usedServices = new Set();
  const seenNamespaces = new Set();
  const seenTopics = new Set();
  const namespaces = Array.isArray(catalog.namespaces) ? catalog.namespaces : [];
  if (namespaces.length === 0) {
    err("namespaces must be a non-empty list");
  }

  for (const ns of namespaces) {
    const where = `namespace ${ns?.namespace ?? "<missing>"}`;
    if (!NAMESPACE_PATTERN.test(ns?.namespace ?? "")) {
      err(`${where}: must match evt.<ctx>.<aggregate>`);
      continue;
    }
    if (seenNamespaces.has(ns.namespace)) {
      err(`${where}: declared twice`);
    }
    seenNamespaces.add(ns.namespace);

    // Ownership: the owner is the only producer and must own this namespace in the manifest.
    const owner = ns.owner;
    usedServices.add(owner);
    const row = manifest.get(owner);
    if (!row) {
      err(`${where}: owner ${owner} is not in the bootstrap manifest`);
    } else if (row.event_namespace !== ns.namespace) {
      err(`${where}: owner ${owner} has event namespace ${row.event_namespace} in the bootstrap manifest; a service may only produce to its own namespace`);
    }
    if (!services[owner]) {
      err(`${where}: owner ${owner} has no entry under services`);
    }
    if (ns.producers !== undefined) {
      const producers = Array.isArray(ns.producers) ? ns.producers : [];
      if (producers.length !== 1 || producers[0] !== owner) {
        err(`${where}: producers must be exactly [${owner}] (owner-only produce); remove the field to default to the owner`);
      }
    }
    if (typeof ns.aggregate !== "string" || !/^[A-Z][A-Za-z]*$/.test(ns.aggregate)) {
      err(`${where}: aggregate must be the PascalCase aggregate name used in eventType`);
    }
    if (!IMPLEMENTATIONS.includes(ns.implementation)) {
      err(`${where}: implementation must be one of ${IMPLEMENTATIONS.join(", ")}`);
    }
    if (typeof ns.contract !== "string" || !/^asyncapi\/svc-[a-z0-9-]+\.yaml$/.test(ns.contract)) {
      err(`${where}: contract must reference asyncapi/<service-id>.yaml`);
    } else if (ns.contract !== `asyncapi/${owner}.yaml`) {
      err(`${where}: contract ${ns.contract} does not belong to owner ${owner}`);
    }

    if (ns.dlq !== undefined) {
      if (ns.dlq === null || typeof ns.dlq !== "object") {
        err(`${where}: dlq must be a mapping with partitions and/or retentionMs`);
      } else {
        for (const key of Object.keys(ns.dlq)) {
          if (!["partitions", "retentionMs"].includes(key)) {
            err(`${where}: dlq.${key} is not supported (partitions, retentionMs)`);
          } else if (!isPositiveInt(ns.dlq[key])) {
            err(`${where}: dlq.${key} must be a positive integer`);
          }
        }
      }
    }

    const topics = Array.isArray(ns.topics) ? ns.topics : [];
    if (topics.length === 0) {
      err(`${where}: topics must be a non-empty list`);
    }
    const nsTopicNames = new Set();
    for (const t of topics) {
      const name = `${ns.namespace}.${t?.event}.v${t?.major}`;
      const twhere = `topic ${name}`;
      if (!EVENT_PATTERN.test(t?.event ?? "") || t.event === "dlq") {
        err(`${twhere}: event must be kebab-case and not 'dlq' (DLQs are derived)`);
      }
      if (!isPositiveInt(t?.major)) {
        err(`${twhere}: major must be a positive integer`);
      }
      if (!TOPIC_PATTERN.test(name)) {
        err(`${twhere}: does not match evt.<ctx>.<aggregate>.<event>.v<major>`);
      }
      if (name.length > MAX_TOPIC_LENGTH) {
        err(`${twhere}: longer than ${MAX_TOPIC_LENGTH} characters`);
      }
      if (seenTopics.has(name)) {
        err(`${twhere}: declared twice`);
      }
      seenTopics.add(name);
      nsTopicNames.add(name);

      if (!EVENT_TYPE_PATTERN.test(t?.eventType ?? "")) {
        err(`${twhere}: eventType must be <Context>.<Aggregate>.<PastTenseEvent>.v<major>`);
      } else {
        const [, aggregate, eventName, version] = t.eventType.split(".");
        if (version !== `v${t.major}`) {
          err(`${twhere}: eventType version ${version} differs from topic major v${t.major}`);
        }
        if (aggregate !== ns.aggregate) {
          err(`${twhere}: eventType aggregate ${aggregate} differs from namespace aggregate ${ns.aggregate}`);
        }
        if (EVENT_PATTERN.test(t.event ?? "") && eventName !== kebabToPascal(t.event)) {
          err(`${twhere}: eventType event ${eventName} does not match topic event ${t.event} (expected ${kebabToPascal(t.event)})`);
        }
      }
      if (t.cleanupPolicy !== undefined && t.cleanupPolicy !== "delete") {
        err(`${twhere}: cleanupPolicy must be delete for event topics`);
      }
      for (const key of ["partitions", "retentionMs", "maxMessageBytes"]) {
        if (t[key] !== undefined && !isPositiveInt(t[key])) {
          err(`${twhere}: ${key} must be a positive integer`);
        }
      }
    }

    if (!CONSUMER_STATUSES.includes(ns.consumersStatus)) {
      err(`${where}: consumersStatus must be one of ${CONSUMER_STATUSES.join(", ")}`);
    }
    const consumers = Array.isArray(ns.consumers) ? ns.consumers : [];
    if (ns.consumersStatus === "known" && consumers.length === 0) {
      err(`${where}: consumersStatus known requires at least one consumer`);
    }
    for (const c of consumers) {
      const cwhere = `${where} consumer ${c?.service}`;
      usedServices.add(c?.service);
      if (!manifest.has(c?.service)) {
        err(`${cwhere}: not in the bootstrap manifest`);
      }
      if (!services[c?.service]) {
        err(`${cwhere}: no entry under services`);
      }
      const groupPattern = new RegExp(`^cg\\.${escapeRegExp(c?.service ?? "")}\\.[a-z0-9]+(?:-[a-z0-9]+)*\\.v[0-9]+$`);
      if (!groupPattern.test(c?.group ?? "")) {
        err(`${cwhere}: group must be cg.${c?.service}.<purpose>.v<major>`);
      }
      if (typeof c?.evidence !== "string" || c.evidence.trim() === "") {
        err(`${cwhere}: evidence (code or config reference) is required`);
      }
      const ctopics = Array.isArray(c?.topics) ? c.topics : [];
      if (ctopics.length === 0) {
        err(`${cwhere}: topics must list the consumed topics`);
      }
      for (const name of ctopics) {
        if (!nsTopicNames.has(name)) {
          err(`${cwhere}: topic ${name} is not an event topic of ${ns.namespace}`);
        }
      }
    }
  }

  for (const serviceId of Object.keys(services)) {
    if (!usedServices.has(serviceId)) {
      err(`services.${serviceId}: neither owns nor consumes a namespace; remove it`);
    }
  }

  for (const gap of Array.isArray(catalog.gaps) ? catalog.gaps : []) {
    if (seenNamespaces.has(gap?.namespace)) {
      err(`gap ${gap.namespace}: also declared under namespaces`);
    }
    if (typeof gap?.reason !== "string" || gap.reason.trim() === "") {
      err(`gap ${gap?.namespace}: reason is required`);
    }
  }

  return errors;
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ---------------------------------------------------------------------------
// Resolution: flat topic list with defaults applied
// ---------------------------------------------------------------------------

export function resolveTopics(catalog) {
  const d = catalog.defaults;
  const out = [];
  for (const ns of catalog.namespaces) {
    const consumers = ns.consumers ?? [];
    const majors = new Set();
    for (const t of ns.topics) {
      const name = `${ns.namespace}.${t.event}.v${t.major}`;
      majors.add(t.major);
      out.push({
        name,
        kind: "event",
        namespace: ns.namespace,
        owner: ns.owner,
        eventType: t.eventType,
        contract: ns.contract,
        implementation: ns.implementation,
        partitions: t.partitions ?? d.partitions,
        replicationFactor: d.replicationFactor,
        minInsyncReplicas: d.minInsyncReplicas,
        cleanupPolicy: "delete",
        retentionMs: t.retentionMs ?? d.retentionMs,
        maxMessageBytes: t.maxMessageBytes ?? d.maxMessageBytes,
        dlq: dlqName(ns.namespace, t.major),
        producers: [ns.owner],
        consumers: consumers
          .filter((c) => c.topics.includes(name))
          .map((c) => ({ service: c.service, group: c.group }))
          .sort((a, b) => a.service.localeCompare(b.service)),
        consumersStatus: ns.consumersStatus,
      });
    }
    for (const major of [...majors].sort((a, b) => a - b)) {
      const name = dlqName(ns.namespace, major);
      const dlqWriters = sortedUnique(
        consumers.filter((c) => c.topics.some((n) => n.endsWith(`.v${major}`))).map((c) => c.service),
      );
      out.push({
        name,
        kind: "dlq",
        namespace: ns.namespace,
        owner: ns.owner,
        eventType: null,
        contract: ns.contract,
        implementation: ns.implementation,
        partitions: ns.dlq?.partitions ?? d.dlq.partitions,
        replicationFactor: d.replicationFactor,
        minInsyncReplicas: d.minInsyncReplicas,
        cleanupPolicy: "delete",
        retentionMs: ns.dlq?.retentionMs ?? d.dlq.retentionMs,
        maxMessageBytes: d.maxMessageBytes,
        dlq: null,
        // DLQ records are written by the consumer group that gave up.
        producers: dlqWriters,
        consumers: [],
        consumersStatus: ns.consumersStatus,
      });
    }
  }
  return out;
}

/**
 * Per-service access derived from the resolved topics.
 * - owner: write its event topics (nothing else; it does not read its own events)
 * - consumer: read the consumed topics with its declared groups; write and read
 *   the namespace DLQ (it parks poison messages there and redrives them)
 */
export function resolveAccess(catalog) {
  const topics = resolveTopics(catalog);
  const access = new Map();
  const entry = (serviceId) => {
    if (!access.has(serviceId)) {
      access.set(serviceId, { produce: new Set(), consume: new Set(), groups: new Set(), owned: new Set() });
    }
    return access.get(serviceId);
  };
  for (const serviceId of Object.keys(catalog.services ?? {})) {
    entry(serviceId);
  }
  for (const t of topics) {
    if (t.kind === "event") {
      entry(t.owner).produce.add(t.name);
      entry(t.owner).owned.add(`${t.namespace}.`);
      for (const c of t.consumers) {
        const e = entry(c.service);
        e.consume.add(t.name);
        e.groups.add(c.group);
      }
    } else {
      for (const writer of t.producers) {
        entry(writer).produce.add(t.name);
        entry(writer).consume.add(t.name);
      }
    }
  }
  const result = {};
  for (const serviceId of [...access.keys()].sort()) {
    const e = access.get(serviceId);
    const svc = catalog.services?.[serviceId] ?? {};
    result[serviceId] = {
      kubernetes_namespace: svc.k8sNamespace ?? null,
      service_account: svc.serviceAccount ?? null,
      // Exact topics. produce_topic_prefixes is the same grant as evt.<ctx>.<aggregate>.
      // prefixes for modules that grant per owned namespace.
      produce_topics: sortedUnique([...e.produce]),
      produce_topic_prefixes: sortedUnique([...e.owned]),
      consume_topics: sortedUnique([...e.consume]),
      consumer_groups: sortedUnique([...e.groups]),
      // Strimzi ACLs grant the cg.<service-id>. prefix; IAM policies can use the explicit groups.
      consumer_group_prefixes: e.consume.size > 0 ? [`cg.${serviceId}.`] : [],
    };
  }
  return result;
}

// ---------------------------------------------------------------------------
// Renderers
// ---------------------------------------------------------------------------

const YAML_OPTIONS = { lineWidth: 0 };

function yamlDocs(header, docs) {
  const body = docs.map((d) => YAML.stringify(d, YAML_OPTIONS)).join("---\n");
  return `# ${header}\n${body}`;
}

export function renderStrimziTopics(catalog) {
  const { strimziClusterName, strimziNamespace } = catalog.cluster;
  const docs = resolveTopics(catalog).map((t) => ({
    apiVersion: "kafka.strimzi.io/v1beta2",
    kind: "KafkaTopic",
    metadata: {
      name: t.name,
      namespace: strimziNamespace,
      labels: {
        "strimzi.io/cluster": strimziClusterName,
        "app.kubernetes.io/part-of": "fintechbankx-event-streaming",
        "app.kubernetes.io/managed-by": "topic-catalog",
        "fintechbankx.io/topic-kind": t.kind,
        "fintechbankx.io/owner": t.owner,
      },
      annotations: {
        "fintechbankx.io/contract": t.contract,
        ...(t.eventType ? { "fintechbankx.io/event-type": t.eventType } : {}),
        ...(t.dlq ? { "fintechbankx.io/dlq": t.dlq } : {}),
      },
    },
    spec: {
      topicName: t.name,
      partitions: t.partitions,
      replicas: t.replicationFactor,
      config: {
        "cleanup.policy": t.cleanupPolicy,
        "retention.ms": t.retentionMs,
        "min.insync.replicas": t.minInsyncReplicas,
        "max.message.bytes": t.maxMessageBytes,
      },
    },
  }));
  return yamlDocs(GENERATED_HEADER, docs);
}

export function renderStrimziUsers(catalog) {
  const { strimziClusterName, strimziNamespace } = catalog.cluster;
  const access = resolveAccess(catalog);
  const docs = Object.entries(access).map(([serviceId, a]) => {
    const acls = [];
    for (const name of a.produce_topics) {
      acls.push({ resource: { type: "topic", name, patternType: "literal" }, operations: ["Write", "Describe"], host: "*" });
    }
    for (const name of a.consume_topics) {
      acls.push({ resource: { type: "topic", name, patternType: "literal" }, operations: ["Read", "Describe"], host: "*" });
    }
    for (const prefix of a.consumer_group_prefixes) {
      acls.push({ resource: { type: "group", name: prefix, patternType: "prefix" }, operations: ["Read", "Describe"], host: "*" });
    }
    return {
      apiVersion: "kafka.strimzi.io/v1beta2",
      kind: "KafkaUser",
      metadata: {
        name: serviceId,
        namespace: strimziNamespace,
        labels: {
          "strimzi.io/cluster": strimziClusterName,
          "app.kubernetes.io/part-of": "fintechbankx-event-streaming",
          "app.kubernetes.io/managed-by": "topic-catalog",
          "fintechbankx.io/service-id": serviceId,
          "fintechbankx.io/workload-namespace": a.kubernetes_namespace,
        },
        annotations: {
          "fintechbankx.io/service-account": a.service_account,
        },
      },
      spec: {
        authentication: { type: "tls" },
        authorization: { type: "simple", acls },
      },
    };
  });
  return yamlDocs(GENERATED_HEADER, docs);
}

/** Strimzi metrics ConfigMap from the JMX exporter rules (hostPort is for the standalone exporter only). */
export function renderMetricsConfigMap(catalog, jmxRulesText) {
  const rules = YAML.parse(jmxRulesText);
  if (!rules || !Array.isArray(rules.rules) || rules.rules.length === 0) {
    throw new Error("JMX exporter config has no rules");
  }
  const { hostPort: _ignored, ...agentConfig } = rules;
  const doc = {
    apiVersion: "v1",
    kind: "ConfigMap",
    metadata: {
      name: `${catalog.cluster.strimziClusterName}-kafka-metrics`,
      namespace: catalog.cluster.strimziNamespace,
      labels: {
        "app.kubernetes.io/part-of": "fintechbankx-event-streaming",
        "app.kubernetes.io/managed-by": "topic-catalog",
      },
    },
    data: {
      "kafka-metrics-config.yml": YAML.stringify(agentConfig, YAML_OPTIONS),
    },
  };
  return yamlDocs(`${GENERATED_HEADER} Source rules: monitoring/jmx/kafka.yml.`, [doc]);
}

/** Input list for scripts/kafka/create-topics.sh (tab separated). */
export function renderTopicsTsv(catalog) {
  const lines = [
    `# ${GENERATED_HEADER}`,
    "# Read by scripts/kafka/create-topics.sh. Columns (tab separated):",
    "# topic\tkind\tpartitions\treplication_factor\tmin_insync_replicas\tcleanup_policy\tretention_ms\tmax_message_bytes",
  ];
  for (const t of resolveTopics(catalog)) {
    lines.push(
      [t.name, t.kind, t.partitions, t.replicationFactor, t.minInsyncReplicas, t.cleanupPolicy, t.retentionMs, t.maxMessageBytes].join("\t"),
    );
  }
  return `${lines.join("\n")}\n`;
}

/** Per-service produce/consume topics for the Terraform msk-client-access module. */
export function renderClientAccessJson(catalog) {
  const doc = {
    _generated: GENERATED_HEADER,
    status: catalog.metadata?.status ?? "Proposed",
    services: resolveAccess(catalog),
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

function mdCell(value) {
  return String(value).replace(/\|/g, "\\|");
}

export function renderMarkdown(catalog) {
  const topics = resolveTopics(catalog);
  const lines = [
    "# Topic catalog (generated)",
    "",
    `<!-- ${GENERATED_HEADER} -->`,
    "",
    `Status: **${catalog.metadata?.status ?? "Proposed"}**. Source: [topics/catalog.yaml](../catalog.yaml).`,
    "Defaults: replication factor " +
      `${catalog.defaults.replicationFactor}, min.insync.replicas ${catalog.defaults.minInsyncReplicas}, ` +
      "cleanup.policy delete. Record key: aggregateId. Producers: the owner only.",
    "",
    "| Topic | Kind | Owner (only producer) | Event type | Partitions | Retention (ms) | DLQ | Known consumers | Implementation |",
    "|---|---|---|---|---|---|---|---|---|",
  ];
  for (const t of topics) {
    const producers = t.kind === "event" ? t.owner : t.producers.length > 0 ? t.producers.join(", ") : "consumers of the namespace (none yet)";
    const consumers =
      t.kind === "dlq"
        ? t.producers.length > 0
          ? `${t.producers.join(", ")} (redrive)`
          : "consumers of the namespace (none yet)"
        : t.consumers.length > 0
          ? t.consumers.map((c) => `${c.service} (\`${c.group}\`)`).join(", ")
          : `${t.consumersStatus} (none in code)`;
    lines.push(
      `| \`${t.name}\` | ${t.kind} | ${mdCell(producers)} | ${t.eventType ? `\`${t.eventType}\`` : "-"} | ${t.partitions} | ${t.retentionMs} | ${t.dlq ? `\`${t.dlq}\`` : "-"} | ${mdCell(consumers)} | ${t.implementation} |`,
    );
  }
  lines.push("", "## Gaps (not provisioned)", "", "| Service | Namespace | Reason |", "|---|---|---|");
  for (const g of catalog.gaps ?? []) {
    lines.push(`| ${g.service} | \`${g.namespace}\` | ${mdCell(g.reason.trim())} |`);
  }
  return `${lines.join("\n")}\n`;
}

/**
 * Every generated file, keyed by repository-relative path.
 * @param {string} root repository root
 */
export function generateAll(root, catalog) {
  const jmx = fs.readFileSync(path.join(root, "monitoring/jmx/kafka.yml"), "utf8");
  return new Map([
    ["deploy/strimzi/generated/kafka-topics.yaml", renderStrimziTopics(catalog)],
    ["deploy/strimzi/generated/kafka-users.yaml", renderStrimziUsers(catalog)],
    ["deploy/strimzi/generated/kafka-metrics-configmap.yaml", renderMetricsConfigMap(catalog, jmx)],
    ["topics/generated/topics.tsv", renderTopicsTsv(catalog)],
    ["topics/generated/msk-client-access.json", renderClientAccessJson(catalog)],
    ["topics/generated/TOPIC_CATALOG.md", renderMarkdown(catalog)],
  ]);
}

// ---------------------------------------------------------------------------
// Optional cross-check against the AsyncAPI catalog (local use; not a CI gate)
// ---------------------------------------------------------------------------

/**
 * Compares catalog topics with the channels of asyncapi/<owner>.yaml files in
 * a checkout of the AsyncAPI catalog. Returns error strings.
 */
export function crossCheckAsyncApi(catalog, asyncapiDir) {
  const errors = [];
  const resolved = resolveTopics(catalog);
  for (const ns of catalog.namespaces) {
    const file = path.join(asyncapiDir, `${ns.owner}.yaml`);
    if (!fs.existsSync(file)) {
      errors.push(`${ns.namespace}: contract ${ns.owner}.yaml not found in ${asyncapiDir}`);
      continue;
    }
    const spec = YAML.parse(fs.readFileSync(file, "utf8"));
    if (spec?.info?.["x-event-namespace"] && spec.info["x-event-namespace"] !== ns.namespace) {
      errors.push(`${ns.namespace}: contract declares x-event-namespace ${spec.info["x-event-namespace"]}`);
    }
    const channels = new Map();
    for (const ch of Object.values(spec?.channels ?? {})) {
      channels.set(ch.address, ch.bindings?.kafka ?? {});
    }
    const expected = resolved.filter((t) => t.namespace === ns.namespace);
    for (const t of expected) {
      const b = channels.get(t.name);
      if (!b) {
        errors.push(`${t.name}: no channel in ${ns.owner}.yaml`);
        continue;
      }
      if (b.partitions !== undefined && b.partitions !== t.partitions) {
        errors.push(`${t.name}: partitions ${t.partitions} in catalog, ${b.partitions} in contract`);
      }
      if (b.replicas !== undefined && b.replicas !== t.replicationFactor) {
        errors.push(`${t.name}: replicas ${t.replicationFactor} in catalog, ${b.replicas} in contract`);
      }
      const cfg = b.topicConfiguration ?? {};
      if (cfg["retention.ms"] !== undefined && cfg["retention.ms"] !== t.retentionMs) {
        errors.push(`${t.name}: retention.ms ${t.retentionMs} in catalog, ${cfg["retention.ms"]} in contract`);
      }
      const policy = cfg["cleanup.policy"];
      if (policy !== undefined && JSON.stringify(policy) !== JSON.stringify([t.cleanupPolicy])) {
        errors.push(`${t.name}: cleanup.policy ${t.cleanupPolicy} in catalog, ${JSON.stringify(policy)} in contract`);
      }
      channels.delete(t.name);
    }
    for (const address of channels.keys()) {
      errors.push(`${address}: channel in ${ns.owner}.yaml but not in the catalog`);
    }
  }
  return errors;
}
