// Topic catalog library: load, validate and render topics/catalog.yaml.
//
// Pure functions (no network, no cluster access). The CLI in generate.mjs
// writes or checks the rendered files; tests in test/catalog.test.mjs.

import fs from "node:fs";
import path from "node:path";
import YAML from "yaml";

// ADR-019 (owner decision 2026-10-08): one topic per aggregate, evt.<ctx>.<aggregate>.v<major>.
// The event is named by its eventType (envelope and record header), not by the topic.
export const AGGREGATE_TOPIC_PATTERN = /^evt\.[a-z]+\.[a-z0-9]+(?:-[a-z0-9]+)*\.v[0-9]+$/;
// Retired form evt.<ctx>.<aggregate>.<event>.v<major>; matched only to reject it with a clear message.
export const PER_EVENT_TOPIC_PATTERN = /^evt\.[a-z]+\.[a-z0-9]+(?:-[a-z0-9]+)*\.(?!dlq\.)[a-z0-9]+(?:-[a-z0-9]+)*\.v[0-9]+$/;
export const DLQ_TOPIC_PATTERN = /^evt\.[a-z]+\.[a-z0-9]+(?:-[a-z0-9]+)*\.dlq\.v[0-9]+$/;
export const NAMESPACE_PATTERN = /^evt\.[a-z]+\.[a-z0-9]+(?:-[a-z0-9]+)*$/;
export const TOPIC_KEYS = ["major", "eventTypes", "partitions", "retentionMs", "maxMessageBytes", "cleanupPolicy"];
export const EVENT_TYPE_PATTERN = /^[A-Z][A-Za-z]*\.[A-Z][A-Za-z]*\.[A-Z][A-Za-z]*\.v[0-9]+$/;
export const SERVICE_ID_PATTERN = /^svc-[a-z]+-[a-z0-9-]+$/;
export const K8S_NAME_PATTERN = /^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/;
export const IMPLEMENTATIONS = ["outbox-relay", "debezium-outbox", "legacy-topic", "contract-only"];
export const CONSUMER_STATUSES = ["known", "unknown"];
export const MAX_TOPIC_LENGTH = 249;

export const GENERATED_HEADER =
  "Generated by scripts/catalog/generate.mjs from topics/catalog.yaml. Do not edit; run `npm run catalog:generate`.";

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

export function loadCatalog(filePath) {
  const doc = YAML.parseDocument(fs.readFileSync(filePath, "utf8"));
  if (doc.errors.length > 0) {
    throw new Error(`${filePath}: ${doc.errors[0].message}`);
  }
  return doc.toJS();
}

/** Parses the bootstrap manifest CSV (no quoted fields in it) into a Map keyed by service_id. */
export function parseManifest(csvText) {
  const lines = csvText.split(/\r?\n/).filter((l) => l.trim() !== "");
  if (lines.length === 0) {
    throw new Error("manifest is empty");
  }
  const header = lines[0].split(",").map((h) => h.trim());
  for (const required of ["service_id", "event_namespace"]) {
    if (!header.includes(required)) {
      throw new Error(`manifest header lacks column ${required}`);
    }
  }
  const rows = new Map();
  for (const line of lines.slice(1)) {
    const cells = line.split(",");
    if (cells.length !== header.length) {
      throw new Error(`manifest row has ${cells.length} cells, header has ${header.length}: ${line}`);
    }
    const row = Object.fromEntries(header.map((h, i) => [h, cells[i].trim()]));
    rows.set(row.service_id, row);
  }
  return rows;
}

export function loadManifest(filePath) {
  return parseManifest(fs.readFileSync(filePath, "utf8"));
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function topicName(namespace, major) {
  return `${namespace}.v${major}`;
}

function retiredPerEventTopic(name) {
  return `per-event topic ${name} is retired: one topic per aggregate, evt.<ctx>.<aggregate>.v<major>, with the event named by eventType (ADR-019)`;
}

export function dlqName(namespace, major) {
  return `${namespace}.dlq.v${major}`;
}

function isPositiveInt(value) {
  return Number.isInteger(value) && value > 0;
}

function sortedUnique(values) {
  return [...new Set(values)].sort();
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/**
 * Validates the catalog against the naming standard and the bootstrap
 * manifest. Returns a list of error strings; empty means valid.
 */
export function validateCatalog(catalog, manifest) {
  const errors = [];
  const err = (msg) => errors.push(msg);

  if (!catalog || typeof catalog !== "object") {
    return ["catalog is empty or not a mapping"];
  }
  if (catalog.apiVersion !== "catalog.fintechbankx.io/v1alpha1" || catalog.kind !== "TopicCatalog") {
    err("apiVersion/kind must be catalog.fintechbankx.io/v1alpha1 TopicCatalog");
  }

  const cluster = catalog.cluster ?? {};
  for (const key of ["strimziClusterName", "strimziNamespace"]) {
    if (typeof cluster[key] !== "string" || !K8S_NAME_PATTERN.test(cluster[key])) {
      err(`cluster.${key} must be a Kubernetes name`);
    }
  }

  const d = catalog.defaults ?? {};
  for (const key of ["partitions", "replicationFactor", "minInsyncReplicas", "retentionMs", "maxMessageBytes"]) {
    if (!isPositiveInt(d[key])) {
      err(`defaults.${key} must be a positive integer`);
    }
  }
  if (isPositiveInt(d.minInsyncReplicas) && isPositiveInt(d.replicationFactor) && d.minInsyncReplicas >= d.replicationFactor) {
    err(`defaults.minInsyncReplicas (${d.minInsyncReplicas}) must be lower than replicationFactor (${d.replicationFactor}) so one broker can fail`);
  }
  if (d.cleanupPolicy !== "delete") {
    err("defaults.cleanupPolicy must be delete: domain events are immutable facts, never compacted");
  }
  for (const key of ["partitions", "retentionMs"]) {
    if (!isPositiveInt(d.dlq?.[key])) {
      err(`defaults.dlq.${key} must be a positive integer`);
    }
  }

  const services = catalog.services ?? {};
  for (const [serviceId, svc] of Object.entries(services)) {
    if (!SERVICE_ID_PATTERN.test(serviceId)) {
      err(`services.${serviceId}: not a service id svc-<ctx>-<capability>`);
    }
    if (!manifest.has(serviceId)) {
      err(`services.${serviceId}: not in the bootstrap manifest`);
    } else if (svc?.eventNamespace !== manifest.get(serviceId).event_namespace) {
      err(`services.${serviceId}.eventNamespace must be ${manifest.get(serviceId).event_namespace} (bootstrap manifest)`);
    }
    if (!K8S_NAME_PATTERN.test(svc?.k8sNamespace ?? "")) {
      err(`services.${serviceId}.k8sNamespace must be a Kubernetes name`);
    }
    if (!K8S_NAME_PATTERN.test(svc?.serviceAccount ?? "")) {
      err(`services.${serviceId}.serviceAccount must be a Kubernetes name`);
    }
  }

  const usedServices = new Set();
  const seenNamespaces = new Set();
  const seenTopics = new Set();
  const namespaces = Array.isArray(catalog.namespaces) ? catalog.namespaces : [];
  if (namespaces.length === 0) {
    err("namespaces must be a non-empty list");
  }

  for (const ns of namespaces) {
    const where = `namespace ${ns?.namespace ?? "<missing>"}`;
    if (!NAMESPACE_PATTERN.test(ns?.namespace ?? "")) {
      err(`${where}: must match evt.<ctx>.<aggregate>`);
      continue;
    }
    if (seenNamespaces.has(ns.namespace)) {
      err(`${where}: declared twice`);
    }
    seenNamespaces.add(ns.namespace);

    // Ownership: the owner is the only producer and must own this namespace in the manifest.
    const owner = ns.owner;
    usedServices.add(owner);
    const row = manifest.get(owner);
    if (!row) {
      err(`${where}: owner ${owner} is not in the bootstrap manifest`);
    } else if (row.event_namespace !== ns.namespace) {
      err(`${where}: owner ${owner} has event namespace ${row.event_namespace} in the bootstrap manifest; a service may only produce to its own namespace`);
    }
    if (!services[owner]) {
      err(`${where}: owner ${owner} has no entry under services`);
    }
    if (ns.producers !== undefined) {
      const producers = Array.isArray(ns.producers) ? ns.producers : [];
      if (producers.length !== 1 || producers[0] !== owner) {
        err(`${where}: producers must be exactly [${owner}] (owner-only produce); remove the field to default to the owner`);
      }
    }
    if (typeof ns.aggregate !== "string" || !/^[A-Z][A-Za-z]*$/.test(ns.aggregate)) {
      err(`${where}: aggregate must be the PascalCase aggregate name used in eventType`);
    }
    if (!IMPLEMENTATIONS.includes(ns.implementation)) {
      err(`${where}: implementation must be one of ${IMPLEMENTATIONS.join(", ")}`);
    }
    if (typeof ns.contract !== "string" || !/^asyncapi\/svc-[a-z0-9-]+\.yaml$/.test(ns.contract)) {
      err(`${where}: contract must reference asyncapi/<service-id>.yaml`);
    } else if (ns.contract !== `asyncapi/${owner}.yaml`) {
      err(`${where}: contract ${ns.contract} does not belong to owner ${owner}`);
    }

    if (ns.dlq !== undefined) {
      if (ns.dlq === null || typeof ns.dlq !== "object") {
        err(`${where}: dlq must be a mapping with reserved, partitions and/or retentionMs`);
      } else {
        for (const key of Object.keys(ns.dlq)) {
          if (key === "reserved") {
            if (typeof ns.dlq.reserved !== "boolean") {
              err(`${where}: dlq.reserved must be true or false`);
            }
          } else if (!["partitions", "retentionMs"].includes(key)) {
            err(`${where}: dlq.${key} is not supported (reserved, partitions, retentionMs)`);
          } else if (!isPositiveInt(ns.dlq[key])) {
            err(`${where}: dlq.${key} must be a positive integer`);
          }
        }
      }
    }

    const topics = Array.isArray(ns.topics) ? ns.topics : [];
    if (topics.length === 0) {
      err(`${where}: topics must be a non-empty list`);
    }
    // name -> Set of event types published on it
    const nsTopics = new Map();
    const contexts = new Set();
    for (const t of topics) {
      if (t?.event !== undefined) {
        err(`${where}: ${retiredPerEventTopic(`${ns.namespace}.${t.event}.v${t.major}`)}; list the event type under eventTypes of topic v${t.major}`);
        continue;
      }
      const name = topicName(ns.namespace, t?.major);
      const twhere = `topic ${name}`;
      for (const key of Object.keys(t ?? {})) {
        if (!TOPIC_KEYS.includes(key)) {
          err(`${twhere}: ${key} is not supported (${TOPIC_KEYS.join(", ")}); the record key is always aggregateId`);
        }
      }
      if (!isPositiveInt(t?.major)) {
        err(`${twhere}: major must be a positive integer`);
      }
      if (!AGGREGATE_TOPIC_PATTERN.test(name)) {
        err(`${twhere}: does not match evt.<ctx>.<aggregate>.v<major>`);
      }
      if (name.length > MAX_TOPIC_LENGTH) {
        err(`${twhere}: longer than ${MAX_TOPIC_LENGTH} characters`);
      }
      if (seenTopics.has(name)) {
        err(`${twhere}: declared twice`);
      }
      seenTopics.add(name);

      const eventTypes = Array.isArray(t?.eventTypes) ? t.eventTypes : [];
      const typeSet = new Set();
      nsTopics.set(name, typeSet);
      if (eventTypes.length === 0) {
        err(`${twhere}: eventTypes must list every event type published on the topic`);
      }
      for (const eventType of eventTypes) {
        if (typeSet.has(eventType)) {
          err(`${twhere}: ${eventType} listed twice`);
        }
        typeSet.add(eventType);
        if (!EVENT_TYPE_PATTERN.test(eventType ?? "")) {
          err(`${twhere}: eventType ${eventType} must be <Context>.<Aggregate>.<PastTenseEvent>.v<major>`);
          continue;
        }
        // The event's major is independent of the topic's major (ADR-019 section 5).
        const [context, aggregate] = eventType.split(".");
        if (aggregate !== ns.aggregate) {
          err(`${twhere}: eventType aggregate ${aggregate} differs from namespace aggregate ${ns.aggregate} (${eventType})`);
        }
        contexts.add(context);
      }
      if (t.cleanupPolicy !== undefined && t.cleanupPolicy !== "delete") {
        err(`${twhere}: cleanupPolicy must be delete for event topics`);
      }
      for (const key of ["partitions", "retentionMs", "maxMessageBytes"]) {
        if (t[key] !== undefined && !isPositiveInt(t[key])) {
          err(`${twhere}: ${key} must be a positive integer`);
        }
      }
    }
    if (contexts.size > 1) {
      const [first, ...rest] = [...contexts];
      err(`${where}: eventType context ${rest.join(", ")} differs from ${first}; one namespace has one context`);
    }

    if (!CONSUMER_STATUSES.includes(ns.consumersStatus)) {
      err(`${where}: consumersStatus must be one of ${CONSUMER_STATUSES.join(", ")}`);
    }
    const consumers = Array.isArray(ns.consumers) ? ns.consumers : [];
    if (ns.consumersStatus === "known" && consumers.length === 0) {
      err(`${where}: consumersStatus known requires at least one consumer`);
    }
    for (const c of consumers) {
      const cwhere = `${where} consumer ${c?.service}`;
      usedServices.add(c?.service);
      if (!manifest.has(c?.service)) {
        err(`${cwhere}: not in the bootstrap manifest`);
      }
      if (!services[c?.service]) {
        err(`${cwhere}: no entry under services`);
      }
      const groupPattern = new RegExp(`^cg\\.${escapeRegExp(c?.service ?? "")}\\.[a-z0-9]+(?:-[a-z0-9]+)*\\.v[0-9]+$`);
      if (!groupPattern.test(c?.group ?? "")) {
        err(`${cwhere}: group must be cg.${c?.service}.<purpose>.v<major>`);
      }
      if (typeof c?.evidence !== "string" || c.evidence.trim() === "") {
        err(`${cwhere}: evidence (code or config reference) is required`);
      }
      const ctopics = Array.isArray(c?.topics) ? c.topics : [];
      if (ctopics.length === 0) {
        err(`${cwhere}: topics must list the consumed topics`);
      }
      for (const name of ctopics) {
        if (PER_EVENT_TOPIC_PATTERN.test(name ?? "")) {
          err(`${cwhere}: ${retiredPerEventTopic(name)}`);
        } else if (!nsTopics.has(name)) {
          err(`${cwhere}: topic ${name} is not an event topic of ${ns.namespace}`);
        }
      }
      // A consumer handles the event types it names and skips every other type on the topic:
      // it commits the offset and never dead-letters an unknown type (ADR-019 section 3).
      const handled = Array.isArray(c?.eventTypes) ? c.eventTypes : [];
      if (handled.length === 0) {
        err(`${cwhere}: eventTypes must list the event types it handles (it skips all others)`);
      }
      for (const eventType of handled) {
        if (!ctopics.some((name) => nsTopics.get(name)?.has(eventType))) {
          err(`${cwhere}: handles ${eventType}, which is not published on ${ctopics.join(", ") || "<no topic>"}`);
        }
      }
      if (c?.dlq !== undefined) {
        // DLQs are consumer-owned (ADR-019): a consumer dead-letters into the DLQ of
        // its own namespace, never into the source topic's namespace.
        const majors = [...new Set(ctopics.map((n) => n.slice(n.lastIndexOf(".v") + 2)))];
        const ownNs = services[c?.service]?.eventNamespace;
        const allowed = ownNs ? majors.map((m) => dlqName(ownNs, m)) : [];
        if (majors.length !== 1 || !allowed.includes(c.dlq)) {
          err(`${cwhere}: dlq ${c.dlq} is outside its own namespace; consumer-owned DLQs only (expected ${allowed.join(", ") || "<own namespace>.dlq.v<major>"})`);
        }
      }
    }
  }

  for (const serviceId of Object.keys(services)) {
    if (!usedServices.has(serviceId)) {
      err(`services.${serviceId}: neither owns nor consumes a namespace; remove it`);
    }
  }

  for (const gap of Array.isArray(catalog.gaps) ? catalog.gaps : []) {
    if (seenNamespaces.has(gap?.namespace)) {
      err(`gap ${gap.namespace}: also declared under namespaces`);
    }
    if (typeof gap?.reason !== "string" || gap.reason.trim() === "") {
      err(`gap ${gap?.namespace}: reason is required`);
    }
  }

  return errors;
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ---------------------------------------------------------------------------
// Resolution: flat topic list with defaults applied
// ---------------------------------------------------------------------------

export function resolveTopics(catalog) {
  const d = catalog.defaults;
  const events = [];
  const dlqs = new Map();
  const dlqRecord = (name, namespace, owner, extra) => ({
    name,
    kind: "dlq",
    namespace,
    owner,
    eventTypes: [],
    partitions: d.dlq.partitions,
    replicationFactor: d.replicationFactor,
    minInsyncReplicas: d.minInsyncReplicas,
    cleanupPolicy: "delete",
    retentionMs: d.dlq.retentionMs,
    maxMessageBytes: d.maxMessageBytes,
    dlq: null,
    // DLQ records are written by the consumer groups that gave up.
    producers: [],
    consumers: [],
    ...extra,
  });

  const namespaceDlq = (ns, name) =>
    dlqRecord(name, ns.namespace, ns.owner, {
      contract: ns.contract,
      implementation: ns.implementation,
      partitions: ns.dlq?.partitions ?? d.dlq.partitions,
      retentionMs: ns.dlq?.retentionMs ?? d.dlq.retentionMs,
      consumersStatus: ns.consumersStatus,
    });

  for (const ns of catalog.namespaces) {
    const consumers = ns.consumers ?? [];
    const majors = new Set();
    for (const t of ns.topics) {
      const name = topicName(ns.namespace, t.major);
      majors.add(t.major);
      events.push({
        name,
        kind: "event",
        namespace: ns.namespace,
        owner: ns.owner,
        eventTypes: [...t.eventTypes],
        contract: ns.contract,
        implementation: ns.implementation,
        partitions: t.partitions ?? d.partitions,
        replicationFactor: d.replicationFactor,
        minInsyncReplicas: d.minInsyncReplicas,
        cleanupPolicy: "delete",
        retentionMs: t.retentionMs ?? d.retentionMs,
        maxMessageBytes: t.maxMessageBytes ?? d.maxMessageBytes,
        // Consumer-owned DLQs (ADR-019): each consumer has its own, so the topic names none.
        dlq: null,
        producers: [ns.owner],
        consumers: consumers
          .filter((c) => c.topics.includes(name))
          .map((c) => ({
            service: c.service,
            group: c.group,
            eventTypes: (c.eventTypes ?? []).filter((e) => t.eventTypes.includes(e)),
            dlq: consumerDlq(catalog, c, t.major),
          }))
          .sort((a, b) => a.service.localeCompare(b.service)),
        consumersStatus: ns.consumersStatus,
      });
    }
    // A namespace DLQ exists only when its own service consumes something (below), or when the
    // owner reserves it ahead of its first consumer.
    if (ns.dlq?.reserved === true) {
      for (const major of [...majors].sort((a, b) => a - b)) {
        const name = dlqName(ns.namespace, major);
        dlqs.set(name, namespaceDlq(ns, name));
      }
    }
  }

  // Writers, and the DLQs of consumers' own namespaces.
  const consumerOwned = [];
  for (const t of events) {
    for (const c of t.consumers) {
      if (!dlqs.has(c.dlq)) {
        const namespace = c.dlq.slice(0, c.dlq.indexOf(".dlq.v"));
        const ns = catalog.namespaces.find((n) => n.namespace === namespace);
        if (ns) {
          dlqs.set(c.dlq, namespaceDlq(ns, c.dlq));
        } else {
          const record = dlqRecord(c.dlq, namespace, c.service, {
            contract: null,
            implementation: "consumer-dlq",
            consumersStatus: "known",
          });
          dlqs.set(c.dlq, record);
          consumerOwned.push(record);
        }
      }
      const record = dlqs.get(c.dlq);
      record.producers = sortedUnique([...record.producers, c.service]);
    }
  }

  const out = [];
  for (const ns of catalog.namespaces) {
    out.push(...events.filter((t) => t.namespace === ns.namespace));
    out.push(...[...dlqs.values()].filter((t) => t.namespace === ns.namespace && !consumerOwned.includes(t)));
  }
  out.push(...consumerOwned.sort((a, b) => a.name.localeCompare(b.name)));
  return out;
}

/** DLQ a consumer writes for a consumed topic of the given major version: always its own namespace's (ADR-019). */
export function consumerDlq(catalog, consumer, major) {
  return dlqName(catalog.services[consumer.service].eventNamespace, major);
}

/**
 * Per-service access derived from the resolved topics.
 * - owner: write its event topics (nothing else; it does not read its own events)
 * - consumer: read the consumed topics with its declared groups; write and read
 *   the DLQ of its own namespace (consumer-owned DLQs, ADR-019)
 */
export function resolveAccess(catalog) {
  const topics = resolveTopics(catalog);
  const access = new Map();
  const entry = (serviceId) => {
    if (!access.has(serviceId)) {
      access.set(serviceId, { produce: new Set(), consume: new Set(), groups: new Set(), owned: new Set() });
    }
    return access.get(serviceId);
  };
  for (const serviceId of Object.keys(catalog.services ?? {})) {
    entry(serviceId);
  }
  for (const t of topics) {
    if (t.kind === "event") {
      entry(t.owner).produce.add(t.name);
      entry(t.owner).owned.add(`${t.namespace}.`);
      for (const c of t.consumers) {
        const e = entry(c.service);
        e.consume.add(t.name);
        e.groups.add(c.group);
      }
    } else {
      for (const writer of t.producers) {
        entry(writer).produce.add(t.name);
        entry(writer).consume.add(t.name);
        // Only the namespace's own service writes its DLQ, so the owned prefix covers it.
        entry(writer).owned.add(`${t.namespace}.`);
      }
    }
  }
  const result = {};
  for (const serviceId of [...access.keys()].sort()) {
    const e = access.get(serviceId);
    const svc = catalog.services?.[serviceId] ?? {};
    result[serviceId] = {
      kubernetes_namespace: svc.k8sNamespace ?? null,
      service_account: svc.serviceAccount ?? null,
      // Exact topics. produce_topic_prefixes is the same grant as evt.<ctx>.<aggregate>.
      // prefixes for modules that grant per owned namespace.
      produce_topics: sortedUnique([...e.produce]),
      produce_topic_prefixes: sortedUnique([...e.owned]),
      consume_topics: sortedUnique([...e.consume]),
      consumer_groups: sortedUnique([...e.groups]),
      // Strimzi ACLs grant the cg.<service-id>. prefix; IAM policies can use the explicit groups.
      consumer_group_prefixes: e.consume.size > 0 ? [`cg.${serviceId}.`] : [],
    };
  }
  return result;
}

// ---------------------------------------------------------------------------
// Renderers
// ---------------------------------------------------------------------------

const YAML_OPTIONS = { lineWidth: 0 };

function yamlDocs(header, docs) {
  const body = docs.map((d) => YAML.stringify(d, YAML_OPTIONS)).join("---\n");
  return `# ${header}\n${body}`;
}

export function renderStrimziTopics(catalog) {
  const { strimziClusterName, strimziNamespace } = catalog.cluster;
  const docs = resolveTopics(catalog).map((t) => ({
    apiVersion: "kafka.strimzi.io/v1beta2",
    kind: "KafkaTopic",
    metadata: {
      name: t.name,
      namespace: strimziNamespace,
      labels: {
        "strimzi.io/cluster": strimziClusterName,
        "app.kubernetes.io/part-of": "fintechbankx-event-streaming",
        "app.kubernetes.io/managed-by": "topic-catalog",
        "fintechbankx.io/topic-kind": t.kind,
        "fintechbankx.io/owner": t.owner,
      },
      annotations: {
        ...(t.contract ? { "fintechbankx.io/contract": t.contract } : {}),
        ...(t.eventTypes.length > 0 ? { "fintechbankx.io/event-types": t.eventTypes.join(",") } : {}),
        ...(t.dlq ? { "fintechbankx.io/dlq": t.dlq } : {}),
      },
    },
    spec: {
      topicName: t.name,
      partitions: t.partitions,
      replicas: t.replicationFactor,
      config: {
        "cleanup.policy": t.cleanupPolicy,
        "retention.ms": t.retentionMs,
        "min.insync.replicas": t.minInsyncReplicas,
        "max.message.bytes": t.maxMessageBytes,
      },
    },
  }));
  return yamlDocs(GENERATED_HEADER, docs);
}

export function renderStrimziUsers(catalog) {
  const { strimziClusterName, strimziNamespace } = catalog.cluster;
  const access = resolveAccess(catalog);
  const docs = Object.entries(access).map(([serviceId, a]) => {
    const acls = [];
    for (const name of a.produce_topics) {
      acls.push({ resource: { type: "topic", name, patternType: "literal" }, operations: ["Write", "Describe"], host: "*" });
    }
    for (const name of a.consume_topics) {
      acls.push({ resource: { type: "topic", name, patternType: "literal" }, operations: ["Read", "Describe"], host: "*" });
    }
    for (const prefix of a.consumer_group_prefixes) {
      acls.push({ resource: { type: "group", name: prefix, patternType: "prefix" }, operations: ["Read", "Describe"], host: "*" });
    }
    return {
      apiVersion: "kafka.strimzi.io/v1beta2",
      kind: "KafkaUser",
      metadata: {
        name: serviceId,
        namespace: strimziNamespace,
        labels: {
          "strimzi.io/cluster": strimziClusterName,
          "app.kubernetes.io/part-of": "fintechbankx-event-streaming",
          "app.kubernetes.io/managed-by": "topic-catalog",
          "fintechbankx.io/service-id": serviceId,
          "fintechbankx.io/workload-namespace": a.kubernetes_namespace,
        },
        annotations: {
          "fintechbankx.io/service-account": a.service_account,
        },
      },
      spec: {
        authentication: { type: "tls" },
        authorization: { type: "simple", acls },
      },
    };
  });
  return yamlDocs(GENERATED_HEADER, docs);
}

/** Strimzi metrics ConfigMap from the JMX exporter rules (hostPort is for the standalone exporter only). */
export function renderMetricsConfigMap(catalog, jmxRulesText) {
  const rules = YAML.parse(jmxRulesText);
  if (!rules || !Array.isArray(rules.rules) || rules.rules.length === 0) {
    throw new Error("JMX exporter config has no rules");
  }
  const { hostPort: _ignored, ...agentConfig } = rules;
  const doc = {
    apiVersion: "v1",
    kind: "ConfigMap",
    metadata: {
      name: `${catalog.cluster.strimziClusterName}-kafka-metrics`,
      namespace: catalog.cluster.strimziNamespace,
      labels: {
        "app.kubernetes.io/part-of": "fintechbankx-event-streaming",
        "app.kubernetes.io/managed-by": "topic-catalog",
      },
    },
    data: {
      "kafka-metrics-config.yml": YAML.stringify(agentConfig, YAML_OPTIONS),
    },
  };
  return yamlDocs(`${GENERATED_HEADER} Source rules: monitoring/jmx/kafka.yml.`, [doc]);
}

/** Input list for scripts/kafka/create-topics.sh (tab separated). */
export function renderTopicsTsv(catalog) {
  const lines = [
    `# ${GENERATED_HEADER}`,
    "# Read by scripts/kafka/create-topics.sh. Columns (tab separated):",
    "# topic\tkind\tpartitions\treplication_factor\tmin_insync_replicas\tcleanup_policy\tretention_ms\tmax_message_bytes",
  ];
  for (const t of resolveTopics(catalog)) {
    lines.push(
      [t.name, t.kind, t.partitions, t.replicationFactor, t.minInsyncReplicas, t.cleanupPolicy, t.retentionMs, t.maxMessageBytes].join("\t"),
    );
  }
  return `${lines.join("\n")}\n`;
}

/** Per-service produce/consume topics for the Terraform msk-client-access module. */
export function renderClientAccessJson(catalog) {
  const doc = {
    _generated: GENERATED_HEADER,
    status: catalog.metadata?.status ?? "Proposed",
    services: resolveAccess(catalog),
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

function mdCell(value) {
  return String(value).replace(/\|/g, "\\|");
}

export function renderMarkdown(catalog) {
  const topics = resolveTopics(catalog);
  const lines = [
    "# Topic catalog (generated)",
    "",
    `<!-- ${GENERATED_HEADER} -->`,
    "",
    `Status: **${catalog.metadata?.status ?? "Proposed"}**. Source: [topics/catalog.yaml](../catalog.yaml).`,
    "Defaults: replication factor " +
      `${catalog.defaults.replicationFactor}, min.insync.replicas ${catalog.defaults.minInsyncReplicas}, ` +
      "cleanup.policy delete. One topic per aggregate (ADR-019): record key aggregateId (UTF-8); headers eventType, eventId " +
      "and correlationId required, traceparent and x-fapi-interaction-id optional. Consumers skip event types they do not " +
      "handle (commit, never dead-letter). Producers: the owner only.",
    "",
    "| Topic | Kind | Owner (only producer) | Event types (eventType header) | Partitions | Retention (ms) | DLQ | Known consumers (handled event types) | Implementation |",
    "|---|---|---|---|---|---|---|---|---|",
  ];
  for (const t of topics) {
    const producers = t.kind === "event" ? t.owner : t.producers.length > 0 ? t.producers.join(", ") : `${t.owner}, once it consumes (consumer-owned DLQ)`;
    const consumers =
      t.kind === "dlq"
        ? t.producers.length > 0
          ? `${t.producers.join(", ")} (redrive)`
          : "-"
        : t.consumers.length > 0
          ? t.consumers
              .map((c) => `${c.service} (\`${c.group}\`, handles ${c.eventTypes.map((e) => `\`${e}\``).join(", ")}; DLQ \`${c.dlq}\`)`)
              .join(", ")
          : `${t.consumersStatus} (none in code)`;
    lines.push(
      `| \`${t.name}\` | ${t.kind} | ${mdCell(producers)} | ${t.eventTypes.length > 0 ? t.eventTypes.map((e) => `\`${e}\``).join("<br>") : "-"} | ${t.partitions} | ${t.retentionMs} | ${t.dlq ? `\`${t.dlq}\`` : "-"} | ${mdCell(consumers)} | ${t.implementation} |`,
    );
  }
  lines.push("", "## Gaps (not provisioned)", "", "| Service | Namespace | Reason |", "|---|---|---|");
  for (const g of catalog.gaps ?? []) {
    lines.push(`| ${g.service} | \`${g.namespace}\` | ${mdCell(g.reason.trim())} |`);
  }
  return `${lines.join("\n")}\n`;
}

/**
 * Every generated file, keyed by repository-relative path.
 * @param {string} root repository root
 */
export function generateAll(root, catalog) {
  const jmx = fs.readFileSync(path.join(root, "monitoring/jmx/kafka.yml"), "utf8");
  return new Map([
    ["deploy/strimzi/generated/kafka-topics.yaml", renderStrimziTopics(catalog)],
    ["deploy/strimzi/generated/kafka-users.yaml", renderStrimziUsers(catalog)],
    ["deploy/strimzi/generated/kafka-metrics-configmap.yaml", renderMetricsConfigMap(catalog, jmx)],
    ["topics/generated/topics.tsv", renderTopicsTsv(catalog)],
    ["topics/generated/msk-client-access.json", renderClientAccessJson(catalog)],
    ["topics/generated/TOPIC_CATALOG.md", renderMarkdown(catalog)],
  ]);
}

// ---------------------------------------------------------------------------
// Optional cross-check against the AsyncAPI catalog (local use; not a CI gate)
// ---------------------------------------------------------------------------

/** eventType consts of the messages a channel carries (message payload, resolved through local $refs). */
export function channelEventTypes(spec, channel) {
  const resolve = (node) => {
    if (node && typeof node.$ref === "string" && node.$ref.startsWith("#/")) {
      return node.$ref
        .slice(2)
        .split("/")
        .reduce((acc, key) => (acc == null ? acc : acc[key.replace(/~1/g, "/").replace(/~0/g, "~")]), spec);
    }
    return node;
  };
  const found = new Set();
  const walk = (node, depth) => {
    const n = resolve(node);
    if (!n || typeof n !== "object" || depth > 8) {
      return;
    }
    if (typeof n.properties?.eventType?.const === "string") {
      found.add(n.properties.eventType.const);
    }
    for (const key of ["allOf", "oneOf", "anyOf"]) {
      for (const child of Array.isArray(n[key]) ? n[key] : []) {
        walk(child, depth + 1);
      }
    }
  };
  for (const ref of Object.values(channel?.messages ?? {})) {
    walk(resolve(ref)?.payload, 0);
  }
  return found;
}

/**
 * Compares catalog topics with the channels of asyncapi/<owner>.yaml files in
 * a checkout of the AsyncAPI catalog. Returns error strings.
 *
 * One aggregate channel per topic: address, partitions, replicas, retention,
 * cleanup policy, event types (eventType consts of its messages) and declared
 * x-consumers must agree. DLQs are consumer-owned and modelled as a message in
 * the contracts, so DLQ channels are not compared.
 */
export function crossCheckAsyncApi(catalog, asyncapiDir) {
  const errors = [];
  const resolved = resolveTopics(catalog);
  for (const ns of catalog.namespaces) {
    const file = path.join(asyncapiDir, `${ns.owner}.yaml`);
    if (!fs.existsSync(file)) {
      errors.push(`${ns.namespace}: contract ${ns.owner}.yaml not found in ${asyncapiDir}`);
      continue;
    }
    const spec = YAML.parse(fs.readFileSync(file, "utf8"));
    if (spec?.info?.["x-event-namespace"] && spec.info["x-event-namespace"] !== ns.namespace) {
      errors.push(`${ns.namespace}: contract declares x-event-namespace ${spec.info["x-event-namespace"]}`);
    }
    const channels = new Map();
    for (const ch of Object.values(spec?.channels ?? {})) {
      if (DLQ_TOPIC_PATTERN.test(ch?.address ?? "")) {
        continue;
      }
      // Receive-only channels of other namespaces (consumed topics) are checked from the consumer side.
      if (typeof ch?.address === "string" && !ch.address.startsWith(`${ns.namespace}.`)) {
        continue;
      }
      channels.set(ch.address, ch);
    }
    for (const t of resolved.filter((x) => x.namespace === ns.namespace && x.kind === "event")) {
      const ch = channels.get(t.name);
      if (!ch) {
        errors.push(`${t.name}: no channel in ${ns.owner}.yaml`);
        continue;
      }
      channels.delete(t.name);
      const b = ch.bindings?.kafka ?? {};
      if (b.partitions !== undefined && b.partitions !== t.partitions) {
        errors.push(`${t.name}: partitions ${t.partitions} in catalog, ${b.partitions} in contract`);
      }
      if (b.replicas !== undefined && b.replicas !== t.replicationFactor) {
        errors.push(`${t.name}: replicas ${t.replicationFactor} in catalog, ${b.replicas} in contract`);
      }
      const cfg = b.topicConfiguration ?? {};
      if (cfg["retention.ms"] !== undefined && cfg["retention.ms"] !== t.retentionMs) {
        errors.push(`${t.name}: retention.ms ${t.retentionMs} in catalog, ${cfg["retention.ms"]} in contract`);
      }
      const policy = cfg["cleanup.policy"];
      if (policy !== undefined && JSON.stringify(policy) !== JSON.stringify([t.cleanupPolicy])) {
        errors.push(`${t.name}: cleanup.policy ${t.cleanupPolicy} in catalog, ${JSON.stringify(policy)} in contract`);
      }
      const contractTypes = channelEventTypes(spec, ch);
      for (const e of t.eventTypes) {
        if (!contractTypes.has(e)) {
          errors.push(`${t.name}: event type ${e} in catalog, not in contract`);
        }
      }
      for (const e of contractTypes) {
        if (!t.eventTypes.includes(e)) {
          errors.push(`${t.name}: event type ${e} in contract, not in catalog`);
        }
      }
      if (Array.isArray(ch["x-consumers"])) {
        const fmt = (list) => list.map((c) => `${c.service}|${c.group}|${c.dlq}`).sort().join(", ");
        const contract = fmt(ch["x-consumers"].map((c) => ({ service: c.serviceId, group: c.consumerGroup, dlq: c.deadLetterTopic })));
        const catalogSide = fmt(t.consumers);
        if (contract !== catalogSide) {
          errors.push(`${t.name}: x-consumers [${contract}] in contract, [${catalogSide}] in catalog`);
        }
      }
    }
    for (const address of channels.keys()) {
      const hint = PER_EVENT_TOPIC_PATTERN.test(address ?? "") ? ` (${retiredPerEventTopic(address)})` : "";
      errors.push(`${address}: channel in ${ns.owner}.yaml but not in the catalog${hint}`);
    }
  }
  return errors;
}
